name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: ^3.13.4
# 의존성추가s
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
# 의존성추가e 
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
flutter:
  uses-material-design: true
  # 이미지 사용
  assets:
    - assets/images/
  #   - images/a_dot_ham.jpeg
  # 폰트 사용 
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
